import Link from "next/link";
import { notFound } from "next/navigation";
import SiteHeader from "@/app/components/SiteHeader";
import { recipes, getRecipeBySlug } from "@/lib/recipes";

export function generateStaticParams() { return recipes.map((recipe) => ({ slug: recipe.slug })); }

export default function RecipeDetailPage({ params }) {
  const recipe = getRecipeBySlug(params.slug);
  if (!recipe) notFound();
  return <main className="min-h-screen bg-canvas text-ink"><SiteHeader title={recipe.title} /><div className="mx-auto max-w-container px-6 py-14"><Link href="/recipes" className="text-body-sm font-medium text-primary">← Back to recipes</Link><header className="mt-8 border-b border-hairline pb-8"><p className="text-label-md uppercase tracking-[0.2em] text-sage">{recipe.category}</p><h1 className="mt-3 font-serif text-display-mobile md:text-display-lg">{recipe.title}</h1><p className="mt-3 max-w-2xl text-body-lg text-muted">{recipe.subtitle}</p><div className="mt-6 flex flex-wrap gap-3"><span className="rounded-full bg-primary-tint px-3 py-1 text-label-sm text-primary-deep">{recipe.contributor}</span><span className="rounded-full bg-ghost-tint px-3 py-1 text-label-sm text-muted">{recipe.servings} servings</span><span className="rounded-full bg-ghost-tint px-3 py-1 text-label-sm text-muted">{recipe.totalTime} min total</span></div></header><div className="mt-10 grid gap-10 lg:grid-cols-[0.9fr_1.1fr]"><aside className="space-y-8"><div className="overflow-hidden rounded-xl border border-hairline bg-card shadow-e1"><img src={recipe.photo} alt={recipe.title} className="h-72 w-full object-cover" /></div><div className="rounded-xl border border-hairline bg-card p-6 shadow-e1"><h2 className="font-serif text-headline-sm">Ingredients</h2><ul className="mt-4 space-y-2 text-body-md text-muted">{recipe.ingredients.map((ingredient) => <li key={ingredient} className="flex gap-3"><span className="mt-1 h-2.5 w-2.5 shrink-0 rounded-full bg-primary" /><span>{ingredient}</span></li>)}</ul></div></aside><section className="space-y-8"><div className="rounded-xl border border-hairline bg-card p-6 shadow-e1"><h2 className="font-serif text-headline-sm">Method</h2><ol className="mt-5 space-y-4">{recipe.steps.map((step, index) => <li key={step} className="flex gap-4"><span className="flex h-7 w-7 shrink-0 items-center justify-center rounded-full bg-primary text-label-md font-medium text-white">{index + 1}</span><p className="text-body-md text-muted">{step}</p></li>)}</ol></div><div className="rounded-xl border border-hairline bg-card p-6 shadow-e1"><h2 className="font-serif text-headline-sm">Kitchen notes</h2><ul className="mt-4 space-y-3 text-body-md text-muted">{recipe.notes.map((note) => <li key={note} className="flex gap-3"><span className="mt-1 text-primary">✦</span><span>{note}</span></li>)}</ul></div><div className="rounded-xl border border-hairline bg-card p-6 shadow-e1"><h2 className="font-serif text-headline-sm">Provenance</h2><p className="mt-3 text-body-md text-muted">{recipe.provenance}</p></div></section></div></div></main>;
}
